trigger: none
pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: buildAgentRepo
    type: github
    endpoint: t-dever
    name: t-dever/azure-devops-build-agents
    ref: features/addInitialDeployment

variables:
  - group: aviatrix-variables
  - name: storageAccountName
    value: travistestagentstatesa
  - name: imageStorageAccountName
    value: travistestagentimagesa
  - name: imageGalleryName
    value: travistestagentimagegallery
stages:
- stage: DeployBuildAgentResources
  displayName: Deploy Build Agent Resource Group
  jobs:
  - job: DeployBuildAgentResourcesJob
    steps:
    - template: pipelines/deploy.resources.yml@buildAgentRepo
      parameters:
        serviceConnectionName: TRAVIS_CONNECTION
        resourceGroup: travis-test-agent-rg
        location: "South Central US"
        storageAccountName: $(storageAccountName)
        storageContainerName: tfstate
        resourcePrefix: travis-test-agent
        userPrincipalId: "$(userPrincipalId)" # Object ID of your account

- stage: CreateUbuntu20Image
  dependsOn: [DeployBuildAgentResources]
  jobs:
    - template: pipelines/create.images.yml@buildAgentRepo
      parameters:
        serviceConnectionName: TRAVIS_CONNECTION
        tagFilter: ubuntu20
        resourceGroup: travis-test-agent-rg
        imageStorageAccountName: $(imageStorageAccountName)
        location: "South Central US"
        imageGalleryName: $(imageGalleryName)

- stage: CreateUbuntu18Image
  dependsOn: [DeployBuildAgentResources]
  jobs:
    - template: pipelines/create.images.yml@buildAgentRepo
      parameters:
        serviceConnectionName: TRAVIS_CONNECTION
        tagFilter: ubuntu18
        resourceGroup: travis-test-agent-rg
        imageStorageAccountName: $(imageStorageAccountName)
        location: "South Central US"
        imageGalleryName: $(imageGalleryName)

        # storageContainerName: tfstate
        # resourcePrefix: travis-test-agent
        # userPrincipalId: "$(userPrincipalId)" # Object ID of your account


        # scaleSetSpotInstance: false
        # createUbuntu20ScaleSet: false