trigger: none
pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: buildAgentRepo
    type: github
    endpoint: t-dever
    name: t-dever/azure-devops-build-agents
    ref: features/addInitialDeployment

variables:
  - group: build-agents
stages:
- stage: DeployBuildAgentResources
  displayName: Deploy Build Agent Resource Group
  jobs:
  - job: DeployBuildAgentResourcesJob
    steps:
    - template: pipelines/deploy.resources.yml@buildAgentRepo
      parameters:
        serviceConnectionName: TRAVIS_CONNECTION
        resourceGroup: $(resourceGroup)
        tempResourceGroup: $(tempResourceGroup)
        location: $(location)
        storageAccountName: $(storageAccountName)
        storageContainerName: tfstate
        resourcePrefix: $(resourcePrefix)
        userPrincipalId: "$(userPrincipalId)" # Object ID of your account
        imageStorageAccountName: $(imageStorageAccountName)
        imageGalleryName: $(imageGalleryName)

- stage: CreateUbuntu20Image
  dependsOn: [DeployBuildAgentResources]
  jobs:
    - template: pipelines/create.images.yml@buildAgentRepo
      parameters:
        serviceConnectionName: TRAVIS_CONNECTION
        tagFilter: ubuntu20
        resourceGroup: $(resourceGroup)
        tempResourceGroup: $(tempResourceGroup)
        imageStorageAccountName: $(imageStorageAccountName)
        location: $(location)
        imageGalleryName: $(imageGalleryName)

- stage: CreateUbuntu18Image
  dependsOn: [DeployBuildAgentResources]
  jobs:
    - template: pipelines/create.images.yml@buildAgentRepo
      parameters:
        serviceConnectionName: TRAVIS_CONNECTION
        tagFilter: ubuntu18
        resourceGroup: $(resourceGroup)
        tempResourceGroup: $(tempResourceGroup)
        imageStorageAccountName: $(imageStorageAccountName)
        location: $(location)
        imageGalleryName: $(imageGalleryName)

- stage: DeployVMSSInstances
  dependsOn: [CreateUbuntu20Image, CreateUbuntu18Image]
  jobs:
    - job: deployVmssUbuntu20
      steps:
      - template: pipelines/deploy.scale.sets.yml@buildAgentRepo
        parameters:
          serviceConnectionName: TRAVIS_CONNECTION
          resourcePrefix: $(resourcePrefix)
          scaleSetSpotInstance: true
          createUbuntu20ScaleSet: true
          createUbuntu18ScaleSet: true
          storageAccountName: $(storageAccountName)
          imageGalleryName: $(imageGalleryName)