trigger: none
pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: buildAgentRepo
    type: github
    endpoint: t-dever
    name: t-dever/azure-devops-build-agents
    ref: features/addInitialDeployment

variables:
  - group: aviatrix-variables

stages:
- stage: DeployBuildAgentResources
  displayName: Deploy Build Agent Resource Group
  jobs:
  - job: DeployBuildAgentResourcesJob
    steps:
    - template: pipelines/deploy.resources.yml@buildAgentRepo
      parameters:
        serviceConnectionName: TRAVIS_CONNECTION
        resourceGroup: travis-test-agent-rg
        location: "South Central US"
        storageAccountName: travistestagentstatesa
        storageContainerName: tfstate
        resourcePrefix: travis-test-agent
        userPrincipalId: "$(userPrincipalId)" # Object ID of your account


        # scaleSetSpotInstance: false
        # createUbuntu20ScaleSet: false